# Generated by Django 3.2.4 on 2021-06-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_types', models.CharField(choices=[('remote', '1'), ('office', '2')], default='office', max_length=50)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
